"""questoes: add personalizada flag - AI-generated-on-demand questions never
enter the graded pool

`personalizada=True` marks a questão generated by the on-demand personalized
quiz (`questionario_personalizado_service`), grounded in a student's own
conversation text. Such questões are appended to the same `Questionario`
row as the admin's own pool (to keep reusing them across students, avoiding
repeat AI calls), but must never be sampled by `iniciar_tentativa` (the
graded módulo-completion quiz) or `iniciar_tentativa_tema` (the tema review
quiz shown to every student) - a student could otherwise prompt-inject
incorrect/offensive questions into a pool other students are graded on. Only
`questionario_personalizado_service`'s own sampling includes them.

Defaults to false, preserving every existing row (all admin-authored).

Revision ID: 0010
Revises: 0009
Create Date: 2026-09-17

"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0010"
down_revision: Union[str, None] = "0009"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "questoes",
        sa.Column("personalizada", sa.Boolean(), nullable=False, server_default=sa.false()),
    )


def downgrade() -> None:
    op.drop_column("questoes", "personalizada")
